# Understanding Tokenizer

In [16]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

In [18]:
#Tensorflow version
tf.__version__

'2.1.0'

In [ ]:
n_words = 3
tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts(["The sun is shining in June!",
                        "September is grey.",
                        "Life is beautiful in August.",
                        "I like it",
                        "This and other things?"])

In [4]:
print(tokenizer.word_index)

{'is': 1, 'in': 2, 'the': 3, 'sun': 4, 'shining': 5, 'june': 6, 'september': 7, 'grey': 8, 'life': 9, 'beautiful': 10, 'august': 11, 'i': 12, 'like': 13, 'it': 14, 'this': 15, 'and': 16, 'other': 17, 'things': 18}


In [7]:
#Converting Texts to sequences
tokenizer.texts_to_sequences(["June is beautiful and I like it"])
#returns list of a list

[[6, 1, 10, 16, 12, 13, 14]]

In [19]:
token_list = tokenizer.texts_to_sequences(["June is beautiful and I like it"])[0]
#Returns only a list

In [8]:
#Getting word counts or frequencies in the text
tokenizer.word_counts

OrderedDict([('the', 1),
             ('sun', 1),
             ('is', 3),
             ('shining', 1),
             ('in', 2),
             ('june', 1),
             ('september', 1),
             ('grey', 1),
             ('life', 1),
             ('beautiful', 1),
             ('august', 1),
             ('i', 1),
             ('like', 1),
             ('it', 1),
             ('this', 1),
             ('and', 1),
             ('other', 1),
             ('things', 1)])

In [7]:
#Creating matrix from the texts
tokenizer.texts_to_matrix(["June is beautiful and I like it!",
                           "Like August"])

array([[0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0.]])

There are several other methods under tokenizer class within Tensorflow 2.1.0. Detailed information about those methods is available in the link: https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer

# Demonstrating Tokenizer with LSTM, Word2Vec Glovebox and Embedding Layer

In [8]:
#from tensorflow.keras import sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM

In [9]:
texts = ["The sun is shining in June!",
         "September is grey.",
         "Life is beautiful in August.",
         "I like it",
         "This and other things?"]

In [10]:
X = tokenizer.texts_to_matrix(texts)
y = [1, 0, 0, 0, 0] 

In [11]:
vocab_size = len(tokenizer.word_index) + 1

# Using simple ANN

In [15]:
model = Sequential()
model.add(Dense(10, input_dim = vocab_size))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = "binary_crossentropy", optimizer = 'rmsprop')

model.fit(X, np.array(y), batch_size = 200, epochs = 100, verbose = 0, validation_split = 0.2, shuffle = True)

understanding Embedding layer -> an Embedding layer converts the sparse vector/matrix into a non-sparse vector (dimensionality reduction)

In [17]:
import numpy as np
model = Sequential()
model.add(Embedding(2,2, input_length = 7))
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop')
model.predict(np.array([[0,1,0,1,1,0,0]]))

array([[[ 0.04173822,  0.01336123],
        [-0.00798082, -0.03987876],
        [ 0.04173822,  0.01336123],
        [-0.00798082, -0.03987876],
        [-0.00798082, -0.03987876],
        [ 0.04173822,  0.01336123],
        [ 0.04173822,  0.01336123]]], dtype=float32)

In [18]:
model.layers[0].get_weights()

[array([[ 0.04173822,  0.01336123],
        [-0.00798082, -0.03987876]], dtype=float32)]

# ANN with Embedding Layer

In [19]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = X.shape[1]))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop')

model.fit(X, np.array(y), batch_size = 100, epochs = 100, 
          verbose = 2, validation_split = 0.2, 
          shuffle = True )

Train on 4 samples, validate on 1 samples
Epoch 1/100
4/4 - 0s - loss: 0.6904 - val_loss: 0.6770
Epoch 2/100
4/4 - 0s - loss: 0.6826 - val_loss: 0.6740
Epoch 3/100
4/4 - 0s - loss: 0.6769 - val_loss: 0.6715
Epoch 4/100
4/4 - 0s - loss: 0.6721 - val_loss: 0.6692
Epoch 5/100
4/4 - 0s - loss: 0.6678 - val_loss: 0.6671
Epoch 6/100
4/4 - 0s - loss: 0.6637 - val_loss: 0.6650
Epoch 7/100
4/4 - 0s - loss: 0.6598 - val_loss: 0.6629
Epoch 8/100
4/4 - 0s - loss: 0.6560 - val_loss: 0.6607
Epoch 9/100
4/4 - 0s - loss: 0.6523 - val_loss: 0.6585
Epoch 10/100
4/4 - 0s - loss: 0.6486 - val_loss: 0.6562
Epoch 11/100
4/4 - 0s - loss: 0.6449 - val_loss: 0.6539
Epoch 12/100
4/4 - 0s - loss: 0.6412 - val_loss: 0.6514
Epoch 13/100
4/4 - 0s - loss: 0.6375 - val_loss: 0.6488
Epoch 14/100
4/4 - 0s - loss: 0.6338 - val_loss: 0.6462
Epoch 15/100
4/4 - 0s - loss: 0.6300 - val_loss: 0.6435
Epoch 16/100
4/4 - 0s - loss: 0.6263 - val_loss: 0.6407
Epoch 17/100
4/4 - 0s - loss: 0.6225 - val_loss: 0.6378
Epoch 18/100
4/

In [20]:
np.round(model.predict(X))

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

# LSTM with Embedding Layer

In [21]:
model = Sequential()

model.add(Embedding(vocab_size, 10, input_length = X.shape[1]))
model.add(LSTM(5))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop')
model.fit(X, np.array(y), batch_size = 200, epochs = 700, verbose = 2, validation_split = 0.2, shuffle = True)

Train on 4 samples, validate on 1 samples
Epoch 1/700
4/4 - 2s - loss: 0.6814 - val_loss: 0.6738
Epoch 2/700
4/4 - 0s - loss: 0.6757 - val_loss: 0.6648
Epoch 3/700
4/4 - 0s - loss: 0.6713 - val_loss: 0.6568
Epoch 4/700
4/4 - 0s - loss: 0.6675 - val_loss: 0.6494
Epoch 5/700
4/4 - 0s - loss: 0.6639 - val_loss: 0.6422
Epoch 6/700
4/4 - 0s - loss: 0.6606 - val_loss: 0.6352
Epoch 7/700
4/4 - 0s - loss: 0.6574 - val_loss: 0.6282
Epoch 8/700
4/4 - 0s - loss: 0.6542 - val_loss: 0.6213
Epoch 9/700
4/4 - 0s - loss: 0.6511 - val_loss: 0.6144
Epoch 10/700
4/4 - 0s - loss: 0.6481 - val_loss: 0.6075
Epoch 11/700
4/4 - 0s - loss: 0.6451 - val_loss: 0.6005
Epoch 12/700
4/4 - 0s - loss: 0.6421 - val_loss: 0.5934
Epoch 13/700
4/4 - 0s - loss: 0.6391 - val_loss: 0.5862
Epoch 14/700
4/4 - 0s - loss: 0.6361 - val_loss: 0.5790
Epoch 15/700
4/4 - 0s - loss: 0.6332 - val_loss: 0.5716
Epoch 16/700
4/4 - 0s - loss: 0.6302 - val_loss: 0.5642
Epoch 17/700
4/4 - 0s - loss: 0.6272 - val_loss: 0.5567
Epoch 18/700
4/

Epoch 146/700
4/4 - 0s - loss: 0.3645 - val_loss: 0.1737
Epoch 147/700
4/4 - 0s - loss: 0.3600 - val_loss: 0.1740
Epoch 148/700
4/4 - 0s - loss: 0.3556 - val_loss: 0.1701
Epoch 149/700
4/4 - 0s - loss: 0.3512 - val_loss: 0.1708
Epoch 150/700
4/4 - 0s - loss: 0.3468 - val_loss: 0.1668
Epoch 151/700
4/4 - 0s - loss: 0.3425 - val_loss: 0.1675
Epoch 152/700
4/4 - 0s - loss: 0.3381 - val_loss: 0.1639
Epoch 153/700
4/4 - 0s - loss: 0.3337 - val_loss: 0.1643
Epoch 154/700
4/4 - 0s - loss: 0.3294 - val_loss: 0.1610
Epoch 155/700
4/4 - 0s - loss: 0.3251 - val_loss: 0.1612
Epoch 156/700
4/4 - 0s - loss: 0.3208 - val_loss: 0.1582
Epoch 157/700
4/4 - 0s - loss: 0.3166 - val_loss: 0.1583
Epoch 158/700
4/4 - 0s - loss: 0.3124 - val_loss: 0.1555
Epoch 159/700
4/4 - 0s - loss: 0.3082 - val_loss: 0.1556
Epoch 160/700
4/4 - 0s - loss: 0.3041 - val_loss: 0.1528
Epoch 161/700
4/4 - 0s - loss: 0.3001 - val_loss: 0.1530
Epoch 162/700
4/4 - 0s - loss: 0.2960 - val_loss: 0.1503
Epoch 163/700
4/4 - 0s - loss: 

Epoch 290/700
4/4 - 0s - loss: 0.0795 - val_loss: 0.0686
Epoch 291/700
4/4 - 0s - loss: 0.0789 - val_loss: 0.0683
Epoch 292/700
4/4 - 0s - loss: 0.0783 - val_loss: 0.0678
Epoch 293/700
4/4 - 0s - loss: 0.0778 - val_loss: 0.0675
Epoch 294/700
4/4 - 0s - loss: 0.0772 - val_loss: 0.0670
Epoch 295/700
4/4 - 0s - loss: 0.0766 - val_loss: 0.0668
Epoch 296/700
4/4 - 0s - loss: 0.0761 - val_loss: 0.0663
Epoch 297/700
4/4 - 0s - loss: 0.0755 - val_loss: 0.0660
Epoch 298/700
4/4 - 0s - loss: 0.0750 - val_loss: 0.0655
Epoch 299/700
4/4 - 0s - loss: 0.0744 - val_loss: 0.0653
Epoch 300/700
4/4 - 0s - loss: 0.0739 - val_loss: 0.0648
Epoch 301/700
4/4 - 0s - loss: 0.0734 - val_loss: 0.0646
Epoch 302/700
4/4 - 0s - loss: 0.0728 - val_loss: 0.0641
Epoch 303/700
4/4 - 0s - loss: 0.0723 - val_loss: 0.0639
Epoch 304/700
4/4 - 0s - loss: 0.0718 - val_loss: 0.0634
Epoch 305/700
4/4 - 0s - loss: 0.0713 - val_loss: 0.0631
Epoch 306/700
4/4 - 0s - loss: 0.0708 - val_loss: 0.0627
Epoch 307/700
4/4 - 0s - loss: 

Epoch 434/700
4/4 - 0s - loss: 0.0284 - val_loss: 0.0369
Epoch 435/700
4/4 - 0s - loss: 0.0282 - val_loss: 0.0369
Epoch 436/700
4/4 - 0s - loss: 0.0282 - val_loss: 0.0367
Epoch 437/700
4/4 - 0s - loss: 0.0278 - val_loss: 0.0365
Epoch 438/700
4/4 - 0s - loss: 0.0276 - val_loss: 0.0365
Epoch 439/700
4/4 - 0s - loss: 0.0276 - val_loss: 0.0363
Epoch 440/700
4/4 - 0s - loss: 0.0272 - val_loss: 0.0361
Epoch 441/700
4/4 - 0s - loss: 0.0271 - val_loss: 0.0361
Epoch 442/700
4/4 - 0s - loss: 0.0270 - val_loss: 0.0359
Epoch 443/700
4/4 - 0s - loss: 0.0266 - val_loss: 0.0358
Epoch 444/700
4/4 - 0s - loss: 0.0265 - val_loss: 0.0357
Epoch 445/700
4/4 - 0s - loss: 0.0265 - val_loss: 0.0355
Epoch 446/700
4/4 - 0s - loss: 0.0261 - val_loss: 0.0354
Epoch 447/700
4/4 - 0s - loss: 0.0259 - val_loss: 0.0353
Epoch 448/700
4/4 - 0s - loss: 0.0259 - val_loss: 0.0352
Epoch 449/700
4/4 - 0s - loss: 0.0255 - val_loss: 0.0350
Epoch 450/700
4/4 - 0s - loss: 0.0253 - val_loss: 0.0349
Epoch 451/700
4/4 - 0s - loss: 

Epoch 578/700
4/4 - 0s - loss: 0.0105 - val_loss: 0.0231
Epoch 579/700
4/4 - 0s - loss: 0.0104 - val_loss: 0.0230
Epoch 580/700
4/4 - 0s - loss: 0.0103 - val_loss: 0.0230
Epoch 581/700
4/4 - 0s - loss: 0.0103 - val_loss: 0.0230
Epoch 582/700
4/4 - 0s - loss: 0.0102 - val_loss: 0.0228
Epoch 583/700
4/4 - 0s - loss: 0.0101 - val_loss: 0.0227
Epoch 584/700
4/4 - 0s - loss: 0.0100 - val_loss: 0.0227
Epoch 585/700
4/4 - 0s - loss: 0.0100 - val_loss: 0.0226
Epoch 586/700
4/4 - 0s - loss: 0.0099 - val_loss: 0.0226
Epoch 587/700
4/4 - 0s - loss: 0.0099 - val_loss: 0.0225
Epoch 588/700
4/4 - 0s - loss: 0.0098 - val_loss: 0.0224
Epoch 589/700
4/4 - 0s - loss: 0.0097 - val_loss: 0.0224
Epoch 590/700
4/4 - 0s - loss: 0.0097 - val_loss: 0.0223
Epoch 591/700
4/4 - 0s - loss: 0.0096 - val_loss: 0.0222
Epoch 592/700
4/4 - 0s - loss: 0.0095 - val_loss: 0.0222
Epoch 593/700
4/4 - 0s - loss: 0.0095 - val_loss: 0.0221
Epoch 594/700
4/4 - 0s - loss: 0.0094 - val_loss: 0.0221
Epoch 595/700
4/4 - 0s - loss: 

In [22]:
np.round(model.predict(X))

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

# Creating Embedding matrix of the input dataset using pretrained Word2Vec Glovebox

In [62]:
embeddings_index = dict()

f = open('glove.6B.300d.txt', encoding = "utf8")

for line in f:
    values = line.split()
    word = values[0]
    coef = np.asarray(values[1:], dtype = 'float32')
    embeddings_index[word] = coef

In [63]:
f.close()

In [64]:
print('loaded word vectors', len(embeddings_index))

loaded word vectors 400000


In [75]:
embedding_dimension = 20
word_index = tokenizer.word_index

In [76]:
embedding_matrix = np.zeros((len(word_index)+1, embedding_dimension))

for word,i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] =  embedding_vector[:embedding_dimension]

In [77]:
embedding_matrix.shape

(19, 20)

In [99]:
print(embedding_matrix)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.74899995e-01  2.29560003e-01  2.49239996e-01 -2.05119997e-01
  -1.22939996e-01  2.12970003e-02 -2.38150001e-01  1.37370005e-01
  -8.91299993e-02 -2.06069994e+00  3.58429998e-01 -2.03649998e-01
  -1.55180003e-02  2.56280005e-01  2.29629993e-01  1.19850005e-03
  -8.98329973e-01  1.36089996e-01  1.88610002e-01 -3.33590001e-01]
 [-4.43989992e-01  1.28169999e-01 -2.52469987e-01 -1.85819998e-01
  -1.66140005e-01  2.59090006e-01 -2.26779997e-01 -6.92289993e-02
  -7.72039965e-02 -1.58140004e+00  1.07529998e-01  1.51230007e-01
  -3.93709987e-02  2.00599998e-01  1.57920003e-01  4.33239996e-01
  -2.16260001e-01  2.52749994e-02 -1.65920004e-01 -2.91079998e-01]
 [ 4.65

# Creating an Embedding Layer

In [87]:
embedding_layer = Embedding(embedding_matrix.shape[0],
                            embedding_matrix.shape[1], 
                            weights = [embedding_matrix],
                            input_length = 25)

In [88]:
#Padding Sequences

from tensorflow.keras.preprocessing.sequence import pad_sequences
X = tokenizer.texts_to_sequences(texts)
X = pad_sequences(X, maxlen = 25)

# ANN and Embedding layer using Word2Vec

In [90]:

model = Sequential()

#embedding layer

model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.layers[0].trainable = False
model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy')

model.fit(X, np.array(y), 
          batch_size = 20, 
          verbose = 2, 
          epochs = 200,
          validation_split = 0.2, 
          shuffle = False)

Train on 4 samples, validate on 1 samples
Epoch 1/200
4/4 - 0s - loss: 0.7321 - val_loss: 0.7490
Epoch 2/200
4/4 - 0s - loss: 0.7126 - val_loss: 0.7365
Epoch 3/200
4/4 - 0s - loss: 0.6988 - val_loss: 0.7277
Epoch 4/200
4/4 - 0s - loss: 0.6875 - val_loss: 0.7206
Epoch 5/200
4/4 - 0s - loss: 0.6777 - val_loss: 0.7143
Epoch 6/200
4/4 - 0s - loss: 0.6688 - val_loss: 0.7085
Epoch 7/200
4/4 - 0s - loss: 0.6605 - val_loss: 0.7031
Epoch 8/200
4/4 - 0s - loss: 0.6528 - val_loss: 0.6980
Epoch 9/200
4/4 - 0s - loss: 0.6455 - val_loss: 0.6930
Epoch 10/200
4/4 - 0s - loss: 0.6386 - val_loss: 0.6883
Epoch 11/200
4/4 - 0s - loss: 0.6319 - val_loss: 0.6837
Epoch 12/200
4/4 - 0s - loss: 0.6254 - val_loss: 0.6792
Epoch 13/200
4/4 - 0s - loss: 0.6192 - val_loss: 0.6749
Epoch 14/200
4/4 - 0s - loss: 0.6131 - val_loss: 0.6706
Epoch 15/200
4/4 - 0s - loss: 0.6072 - val_loss: 0.6664
Epoch 16/200
4/4 - 0s - loss: 0.6015 - val_loss: 0.6623
Epoch 17/200
4/4 - 0s - loss: 0.5958 - val_loss: 0.6583
Epoch 18/200
4/

Epoch 146/200
4/4 - 0s - loss: 0.1867 - val_loss: 0.3105
Epoch 147/200
4/4 - 0s - loss: 0.1850 - val_loss: 0.3096
Epoch 148/200
4/4 - 0s - loss: 0.1833 - val_loss: 0.3065
Epoch 149/200
4/4 - 0s - loss: 0.1816 - val_loss: 0.3056
Epoch 150/200
4/4 - 0s - loss: 0.1799 - val_loss: 0.3025
Epoch 151/200
4/4 - 0s - loss: 0.1783 - val_loss: 0.3016
Epoch 152/200
4/4 - 0s - loss: 0.1766 - val_loss: 0.2986
Epoch 153/200
4/4 - 0s - loss: 0.1750 - val_loss: 0.2977
Epoch 154/200
4/4 - 0s - loss: 0.1734 - val_loss: 0.2946
Epoch 155/200
4/4 - 0s - loss: 0.1718 - val_loss: 0.2937
Epoch 156/200
4/4 - 0s - loss: 0.1702 - val_loss: 0.2907
Epoch 157/200
4/4 - 0s - loss: 0.1686 - val_loss: 0.2898
Epoch 158/200
4/4 - 0s - loss: 0.1670 - val_loss: 0.2868
Epoch 159/200
4/4 - 0s - loss: 0.1655 - val_loss: 0.2859
Epoch 160/200
4/4 - 0s - loss: 0.1639 - val_loss: 0.2829
Epoch 161/200
4/4 - 0s - loss: 0.1624 - val_loss: 0.2820
Epoch 162/200
4/4 - 0s - loss: 0.1609 - val_loss: 0.2791
Epoch 163/200
4/4 - 0s - loss: 

In [94]:
print(model.summary())

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 25, 20)            380       
_________________________________________________________________
flatten_6 (Flatten)          (None, 500)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 501       
Total params: 881
Trainable params: 501
Non-trainable params: 380
_________________________________________________________________
None


In [92]:
np.round(model.predict(X))

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

# LSTM and Word Embeddings with Word2Vec

In [96]:
model = Sequential()

model.add(embedding_layer)
model.add(LSTM(5))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy')

model.fit(X, np.array(y), 
          batch_size = 20, 
          epochs = 500, 
          verbose = 2, 
          validation_split = 0.2,
          shuffle = False)

Train on 4 samples, validate on 1 samples
Epoch 1/500
4/4 - 2s - loss: 0.6626 - val_loss: 0.6088
Epoch 2/500
4/4 - 0s - loss: 0.6540 - val_loss: 0.5992
Epoch 3/500
4/4 - 0s - loss: 0.6479 - val_loss: 0.5913
Epoch 4/500
4/4 - 0s - loss: 0.6429 - val_loss: 0.5844
Epoch 5/500
4/4 - 0s - loss: 0.6385 - val_loss: 0.5780
Epoch 6/500
4/4 - 0s - loss: 0.6346 - val_loss: 0.5721
Epoch 7/500
4/4 - 0s - loss: 0.6309 - val_loss: 0.5666
Epoch 8/500
4/4 - 0s - loss: 0.6274 - val_loss: 0.5612
Epoch 9/500
4/4 - 0s - loss: 0.6240 - val_loss: 0.5560
Epoch 10/500
4/4 - 0s - loss: 0.6208 - val_loss: 0.5509
Epoch 11/500
4/4 - 0s - loss: 0.6177 - val_loss: 0.5460
Epoch 12/500
4/4 - 0s - loss: 0.6147 - val_loss: 0.5411
Epoch 13/500
4/4 - 0s - loss: 0.6117 - val_loss: 0.5363
Epoch 14/500
4/4 - 0s - loss: 0.6088 - val_loss: 0.5315
Epoch 15/500
4/4 - 0s - loss: 0.6060 - val_loss: 0.5268
Epoch 16/500
4/4 - 0s - loss: 0.6031 - val_loss: 0.5221
Epoch 17/500
4/4 - 0s - loss: 0.6003 - val_loss: 0.5174
Epoch 18/500
4/

Epoch 146/500
4/4 - 0s - loss: 0.2122 - val_loss: 0.1731
Epoch 147/500
4/4 - 0s - loss: 0.2095 - val_loss: 0.1571
Epoch 148/500
4/4 - 0s - loss: 0.2069 - val_loss: 0.1700
Epoch 149/500
4/4 - 0s - loss: 0.2043 - val_loss: 0.1532
Epoch 150/500
4/4 - 0s - loss: 0.2018 - val_loss: 0.1673
Epoch 151/500
4/4 - 0s - loss: 0.1993 - val_loss: 0.1494
Epoch 152/500
4/4 - 0s - loss: 0.1969 - val_loss: 0.1644
Epoch 153/500
4/4 - 0s - loss: 0.1945 - val_loss: 0.1460
Epoch 154/500
4/4 - 0s - loss: 0.1920 - val_loss: 0.1610
Epoch 155/500
4/4 - 0s - loss: 0.1897 - val_loss: 0.1429
Epoch 156/500
4/4 - 0s - loss: 0.1873 - val_loss: 0.1574
Epoch 157/500
4/4 - 0s - loss: 0.1850 - val_loss: 0.1400
Epoch 158/500
4/4 - 0s - loss: 0.1827 - val_loss: 0.1540
Epoch 159/500
4/4 - 0s - loss: 0.1805 - val_loss: 0.1369
Epoch 160/500
4/4 - 0s - loss: 0.1783 - val_loss: 0.1509
Epoch 161/500
4/4 - 0s - loss: 0.1762 - val_loss: 0.1337
Epoch 162/500
4/4 - 0s - loss: 0.1740 - val_loss: 0.1481
Epoch 163/500
4/4 - 0s - loss: 

Epoch 290/500
4/4 - 0s - loss: 0.0522 - val_loss: 0.0465
Epoch 291/500
4/4 - 0s - loss: 0.0519 - val_loss: 0.0390
Epoch 292/500
4/4 - 0s - loss: 0.0514 - val_loss: 0.0459
Epoch 293/500
4/4 - 0s - loss: 0.0511 - val_loss: 0.0385
Epoch 294/500
4/4 - 0s - loss: 0.0506 - val_loss: 0.0453
Epoch 295/500
4/4 - 0s - loss: 0.0503 - val_loss: 0.0380
Epoch 296/500
4/4 - 0s - loss: 0.0498 - val_loss: 0.0447
Epoch 297/500
4/4 - 0s - loss: 0.0495 - val_loss: 0.0375
Epoch 298/500
4/4 - 0s - loss: 0.0491 - val_loss: 0.0441
Epoch 299/500
4/4 - 0s - loss: 0.0487 - val_loss: 0.0370
Epoch 300/500
4/4 - 0s - loss: 0.0483 - val_loss: 0.0435
Epoch 301/500
4/4 - 0s - loss: 0.0480 - val_loss: 0.0365
Epoch 302/500
4/4 - 0s - loss: 0.0476 - val_loss: 0.0429
Epoch 303/500
4/4 - 0s - loss: 0.0472 - val_loss: 0.0361
Epoch 304/500
4/4 - 0s - loss: 0.0469 - val_loss: 0.0423
Epoch 305/500
4/4 - 0s - loss: 0.0465 - val_loss: 0.0356
Epoch 306/500
4/4 - 0s - loss: 0.0461 - val_loss: 0.0418
Epoch 307/500
4/4 - 0s - loss: 

Epoch 434/500
4/4 - 0s - loss: 0.0183 - val_loss: 0.0168
Epoch 435/500
4/4 - 0s - loss: 0.0182 - val_loss: 0.0167
Epoch 436/500
4/4 - 0s - loss: 0.0181 - val_loss: 0.0166
Epoch 437/500
4/4 - 0s - loss: 0.0180 - val_loss: 0.0165
Epoch 438/500
4/4 - 0s - loss: 0.0178 - val_loss: 0.0164
Epoch 439/500
4/4 - 0s - loss: 0.0177 - val_loss: 0.0163
Epoch 440/500
4/4 - 0s - loss: 0.0176 - val_loss: 0.0162
Epoch 441/500
4/4 - 0s - loss: 0.0175 - val_loss: 0.0161
Epoch 442/500
4/4 - 0s - loss: 0.0174 - val_loss: 0.0160
Epoch 443/500
4/4 - 0s - loss: 0.0173 - val_loss: 0.0159
Epoch 444/500
4/4 - 0s - loss: 0.0171 - val_loss: 0.0158
Epoch 445/500
4/4 - 0s - loss: 0.0170 - val_loss: 0.0157
Epoch 446/500
4/4 - 0s - loss: 0.0169 - val_loss: 0.0156
Epoch 447/500
4/4 - 0s - loss: 0.0168 - val_loss: 0.0155
Epoch 448/500
4/4 - 0s - loss: 0.0167 - val_loss: 0.0154
Epoch 449/500
4/4 - 0s - loss: 0.0166 - val_loss: 0.0153
Epoch 450/500
4/4 - 0s - loss: 0.0165 - val_loss: 0.0152
Epoch 451/500
4/4 - 0s - loss: 

In [97]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 25, 20)            380       
_________________________________________________________________
lstm_1 (LSTM)                (None, 5)                 520       
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 6         
Total params: 906
Trainable params: 526
Non-trainable params: 380
_________________________________________________________________


In [98]:
model.predict(X)

array([[0.97886854],
       [0.01020625],
       [0.00741587],
       [0.00812974],
       [0.01103792]], dtype=float32)